/** Textos fixos do bloqueio BETA (Google Maps / Disparador) até liberação pelo admin. */

export const FERRAMENTA_BETA_MSG_LINHA1 =
  "ESTA FERRAMENTA AINDA ESTÁ EM PROCESSO DE CONSTRUÇÃO, E ESTARÁ DISPONÍVEL PARA CONSUMO A PARTIR DE 06/06/2026";

export const FERRAMENTA_BETA_MSG_LINHA2 =
  'ESTA FERRAMENTA, ASSIM COMO "DISPARADOR DE MENSAGENS", NÃO ESTÃO INCLUSAS NO SEU PLANO! PARA QUALQUER DÚVIDA, CONTRATE O SUPORTE';
