// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL?.trim() || !SUPABASE_PUBLISHABLE_KEY?.trim()) {
  throw new Error(
    "Supabase: faltam URL e chave. " +
      "Local: copie .env.example para .env. " +
      "Vercel: Settings → Environment Variables → marque Production (e Preview). " +
      "Nomes: VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, ou SUPABASE_URL + SUPABASE_ANON_KEY. " +
      "Depois: Redeploy sem cache."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const browserSessionStorage =
  typeof globalThis !== "undefined" && typeof (globalThis as unknown as { sessionStorage?: Storage }).sessionStorage !== "undefined"
    ? (globalThis as unknown as { sessionStorage: Storage }).sessionStorage
    : undefined;

/**
 * Persistência de sessão em sessionStorage (por aba) + PKCE.
 * Evita gravar tokens manualmente em localStorage (recomendação de hardening SaaS).
 * Documentação: Auth — storage; Frontend — tokens.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: "pkce",
    storage: browserSessionStorage,
    persistSession: Boolean(browserSessionStorage),
    autoRefreshToken: Boolean(browserSessionStorage),
    detectSessionInUrl: true,
  },
});