// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL?.trim() || !SUPABASE_PUBLISHABLE_KEY?.trim()) {
  throw new Error(
    "Supabase: faltam URL e chave. " +
      "Local: copie .env.example para .env. " +
      "Vercel: Settings → Environment Variables → marque Production (e Preview). " +
      "Nomes: VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, ou SUPABASE_URL + SUPABASE_ANON_KEY. " +
      "Depois: Redeploy sem cache."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const browserSessionStorage =
  typeof globalThis !== "undefined" && typeof (globalThis as unknown as { sessionStorage?: Storage }).sessionStorage !== "undefined"
    ? (globalThis as unknown as { sessionStorage: Storage }).sessionStorage
    : undefined;

/**
 * Persistência de sessão em sessionStorage (por aba) + PKCE.
 *
 * **IMPORTANTE — auth.lock = processLock**:
 * Como cada aba tem a sua própria sessão (sessionStorage), NÃO queremos que o
 * supabase-js use o `navigatorLock` (Web Locks API) por defeito — esse lock é
 * per-origin e, quando uma nova aba abre, o auth-js chama `locks.request(name,
 * { steal: true })` para se tornar líder do refresh, abortando a aba antiga
 * com `AbortError: Lock broken by another request with the 'steal' option.`
 * Esse erro inunda a consola e serializa desnecessariamente chamadas
 * concorrentes a `auth.getSession()` / `getUser()` (lentidão).
 *
 * `processLock` coordena apenas dentro do JS process da aba — que é exactamente
 * o que queremos quando cada aba tem tokens independentes.
 * Ref: Supabase auth-js README — "lock" option.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: "pkce",
    storage: browserSessionStorage,
    persistSession: Boolean(browserSessionStorage),
    autoRefreshToken: Boolean(browserSessionStorage),
    detectSessionInUrl: true,
    lock: processLock,
  },
});