// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { guardedFetch } from './guardedFetch';
import { waitingAuthLock } from './waitingAuthLock';
import { isTabLeader, onTabLeaderChange, startTabLeader } from '@/lib/tabLeader';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL?.trim() || !SUPABASE_PUBLISHABLE_KEY?.trim()) {
  throw new Error(
    "Supabase: faltam URL e chave. " +
      "Local: copie .env.example para .env. " +
      "Vercel: Settings → Environment Variables → marque Production (e Preview). " +
      "Nomes: VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, ou SUPABASE_URL + SUPABASE_ANON_KEY. " +
      "Depois: Redeploy sem cache."
  );
}

const browserLocalStorage =
  typeof globalThis !== "undefined" && typeof (globalThis as unknown as { localStorage?: Storage }).localStorage !== "undefined"
    ? (globalThis as unknown as { localStorage: Storage }).localStorage
    : undefined;

const browserSessionStorage =
  typeof globalThis !== "undefined" && typeof (globalThis as unknown as { sessionStorage?: Storage }).sessionStorage !== "undefined"
    ? (globalThis as unknown as { sessionStorage: Storage }).sessionStorage
    : undefined;

/** Quem ainda tinha sessão por aba passa a partilhar a mesma sessão no browser. */
function migrateAuthFromSessionStorage(): void {
  if (!browserLocalStorage || !browserSessionStorage) return;
  try {
    for (let i = 0; i < browserSessionStorage.length; i += 1) {
      const key = browserSessionStorage.key(i);
      if (!key || !key.startsWith("sb-") || !key.includes("auth-token")) continue;
      if (!browserLocalStorage.getItem(key)) {
        const value = browserSessionStorage.getItem(key);
        if (value) browserLocalStorage.setItem(key, value);
      }
      browserSessionStorage.removeItem(key);
      i -= 1;
    }
  } catch {
    /* ignore */
  }
}

migrateAuthFromSessionStorage();

/**
 * Sessão em localStorage (todas as abas) + lock que espera em vez de abortar.
 * Só a aba líder faz auto-refresh. As outras leem o token já renovado.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: { fetch: guardedFetch },
  auth: {
    flowType: "pkce",
    storage: browserLocalStorage,
    persistSession: Boolean(browserLocalStorage),
    autoRefreshToken: false,
    detectSessionInUrl: true,
    lock: waitingAuthLock,
    lockAcquireTimeout: 60_000,
  },
});

if (typeof window !== "undefined") {
  startTabLeader();
  const applyLeaderRefresh = (leader: boolean) => {
    if (leader) void supabase.auth.startAutoRefresh();
    else void supabase.auth.stopAutoRefresh();
  };
  applyLeaderRefresh(isTabLeader());
  onTabLeaderChange(applyLeaderRefresh);
}
